### ISSUE TITLE
 Your :LocationList fuzzy finder

### ISSUE THREAD

**Issue by snoblenet** [natebosch/dotfiles#1]
Hi Nate,

I've been using your `:LocationList` fuzzy finder successfully for some time.

A while ago, it started returning `Vim(let):E684: list index out of range: 0` errors after I select an item in the list.

It seems the `item` in `items` is not being sent to `Pick()`.

Is this happening to you too?

I've searched recent commits to `fzf` and `fzf.vim` but have found none that I would expect to cause a problem like this.

**Comment by natebosch** [comment]
Hey @snoblenet - so sorry for the silence. I didn't have notifications turned on in this repo.

I haven't hit that problem, I'm on the latest of `fzf` and `fzf.vim` as of today.

I wonder if your fzf behaves differently from mine, maybe with some kind of option you have configured globally?

Is it consistent? You could try adding an `echom a:item` as the first line in `Pick()` to see what format you're getting. It should be a number, then a space, then the line from the quickfix window...

**Comment by snoblenet** [comment]
Thanks. I got it working back then. Can't remember what the issue was sorry.
